version: '3.5'
services:
    web:
        container_name: address-api
        image: mtakashimori/laravel
        command: php artisan serve --host=0.0.0.0 --port=80
        volumes:
            - .:/var/www/html/address-api
        tty: true
        networks:
            main:
                aliases:
                    - web
    db:
      container_name: address-db
      image: mariadb:10.4
      networks:
          main:
              aliases:
                  - db
networks:
    main:
